"""
CognifyX – Planner Agent (Autonomous Decision-Making)
Analyzes the JD, uploaded resume count, and available keywords to dynamically
decide the optimal pipeline strategy using ReAct-style reasoning.

Outputs a PipelinePlan with:
  - Ordered stage list (which stages to run, which to skip)
  - Dynamic weight adjustments (experience vs skills priority)
  - ATS filter aggressiveness (top_n tuning)
  - Recommendations and reasoning transcript
"""
import re
import json


class PipelinePlan:
    """
    Immutable plan generated by the PlannerAgent.
    Consumed by the CoordinatorAgent and the UI to drive pipeline execution.
    """
    def __init__(self):
        # Stage toggles  (True = run, False = skip)
        self.run_ats_filter       = True
        self.run_extraction       = True
        self.run_scoring          = True
        self.run_reflection       = True
        self.run_debate           = True
        self.run_insights         = True

        # Tunables
        self.ats_top_n            = 40    # How many resumes pass ATS
        self.experience_weight    = "normal"   # normal | high | low
        self.skills_weight        = "normal"   # normal | high | low
        self.education_weight     = "normal"   # normal | high | low
        self.composite_weights    = {"ats": 0.25, "keyword": 0.35, "llm": 0.40}
        self.debate_weights       = {"skill": 0.40, "experience": 0.35, "culture": 0.25}

        # Metadata
        self.reasoning_steps      = []   # ReAct trace
        self.jd_complexity        = "standard"  # simple | standard | complex
        self.estimated_time       = "~2 min"
        self.strategy_label       = "Standard Pipeline"
        self.recommendations      = []


class PlannerAgent:
    """
    Autonomous decision-making agent that reasons about the best pipeline
    strategy before execution begins.

    Uses a lightweight ReAct loop:
      THINK  → analyse the inputs
      ACT    → decide stage config
      OBSERVE → validate the decision
    """

    # Keywords signalling seniority / experience emphasis
    SENIORITY_SIGNALS = [
        "senior", "lead", "principal", "staff", "architect", "manager",
        "director", "head of", "vp", "chief", "10+ years", "8+ years",
        "7+ years", "6+ years", "5+ years",
    ]
    JUNIOR_SIGNALS = [
        "junior", "entry", "intern", "fresher", "graduate", "trainee",
        "0-2 years", "1+ year", "new grad",
    ]
    TECHNICAL_SIGNALS = [
        "python", "java", "react", "docker", "kubernetes", "aws", "gcp",
        "machine learning", "deep learning", "data engineer", "devops",
        "full-stack", "backend", "frontend", "algorithm",
    ]
    SOFT_SKILL_SIGNALS = [
        "leadership", "communication", "teamwork", "collaboration",
        "mentorship", "stakeholder", "cross-functional", "culture",
    ]

    def __init__(self, llm_agent=None):
        self.llm_agent = llm_agent

    # ─── ReAct Helpers ────────────────────────────────────────────────

    def _think(self, plan, observation, thought):
        """Record a THINK step in the ReAct trace."""
        plan.reasoning_steps.append({
            "phase": "THINK",
            "observation": observation,
            "thought": thought,
        })

    def _act(self, plan, action, detail):
        """Record an ACT step in the ReAct trace."""
        plan.reasoning_steps.append({
            "phase": "ACT",
            "action": action,
            "detail": detail,
        })

    def _observe(self, plan, result):
        """Record an OBSERVE step in the ReAct trace."""
        plan.reasoning_steps.append({
            "phase": "OBSERVE",
            "result": result,
        })

    # ─── Core Analysis ────────────────────────────────────────────────

    def _analyse_jd(self, job_description):
        """Extract structured signals from the JD text."""
        jd_lower = job_description.lower()
        jd_len = len(job_description)

        # Seniority
        seniority_hits = [s for s in self.SENIORITY_SIGNALS if s in jd_lower]
        junior_hits    = [s for s in self.JUNIOR_SIGNALS if s in jd_lower]

        # Technical depth
        tech_hits = [s for s in self.TECHNICAL_SIGNALS if s in jd_lower]

        # Soft skill emphasis
        soft_hits = [s for s in self.SOFT_SKILL_SIGNALS if s in jd_lower]

        # Experience requirement
        exp_match = re.search(r'(\d+)\s*\+?\s*(?:years|yrs)', jd_lower)
        min_years = int(exp_match.group(1)) if exp_match else 0

        # Education requirement
        edu_required = any(w in jd_lower for w in ["master", "phd", "doctorate", "degree required"])
        edu_preferred = any(w in jd_lower for w in ["degree preferred", "bachelor", "b.sc", "b.tech"])

        return {
            "jd_length": jd_len,
            "seniority_hits": seniority_hits,
            "junior_hits": junior_hits,
            "tech_hits": tech_hits,
            "soft_hits": soft_hits,
            "min_years": min_years,
            "edu_required": edu_required,
            "edu_preferred": edu_preferred,
        }

    def _classify_complexity(self, jd_analysis, resume_count, keyword_count):
        """Classify the overall job complexity."""
        tech_count = len(jd_analysis['tech_hits'])
        jd_len = jd_analysis['jd_length']

        if resume_count > 200 or tech_count >= 6 or jd_len > 3000:
            return "complex"
        elif resume_count < 20 and tech_count <= 2 and jd_len < 500:
            return "simple"
        return "standard"

    # ─── Main Planning Method ─────────────────────────────────────────

    def plan(self, job_description, keywords_input="", resume_count=0):
        """
        Analyse inputs and produce an optimal PipelinePlan.

        Args:
            job_description: Full JD text
            keywords_input:  Comma-separated ATS keywords (may be empty)
            resume_count:    Number of resumes uploaded

        Returns:
            PipelinePlan with stage toggles, weights, and reasoning trace.
        """
        plan = PipelinePlan()
        keywords_list = [k.strip() for k in keywords_input.replace('\n', ',').split(',') if k.strip()]
        keyword_count = len(keywords_list)

        # ── Step 1: Analyse the JD ─────────────────────────────────────
        jd_analysis = self._analyse_jd(job_description)
        plan.jd_complexity = self._classify_complexity(jd_analysis, resume_count, keyword_count)

        self._think(plan,
            f"JD length={jd_analysis['jd_length']} chars, "
            f"{resume_count} resumes, {keyword_count} keywords",
            f"Complexity classification → {plan.jd_complexity}"
        )

        # ── Step 2: Decide ATS aggressiveness ──────────────────────────
        if resume_count > 500:
            plan.ats_top_n = 30
            self._act(plan, "SET ats_top_n=30",
                f"Large dataset ({resume_count} resumes) → aggressive ATS filter "
                f"to keep pipeline fast.")
        elif resume_count > 100:
            plan.ats_top_n = 40
            self._act(plan, "SET ats_top_n=40",
                f"Medium dataset ({resume_count} resumes) → standard ATS filter.")
        elif resume_count <= 15:
            plan.ats_top_n = resume_count  # process all
            self._act(plan, f"SET ats_top_n={resume_count}",
                f"Small dataset ({resume_count} resumes) → skip aggressive filtering, "
                f"process all candidates.")
        else:
            plan.ats_top_n = 40

        self._observe(plan, f"ATS filter set to keep top {plan.ats_top_n}.")

        # ── Step 3: Keywords analysis ──────────────────────────────────
        if keyword_count < 3:
            self._think(plan,
                f"Only {keyword_count} keywords provided.",
                "Low keyword count means ATS keyword-match scoring will be unreliable. "
                "I should reduce keyword weight and increase LLM weight.")
            plan.composite_weights = {"ats": 0.25, "keyword": 0.20, "llm": 0.55}
            self._act(plan, "ADJUST composite_weights: keyword=0.20, llm=0.55",
                "Shifting scoring weight toward LLM analysis because keywords are sparse.")
        elif keyword_count > 15:
            self._think(plan,
                f"{keyword_count} keywords is a rich set.",
                "Many keywords → keyword matching will be very discriminative. "
                "I should increase keyword weight.")
            plan.composite_weights = {"ats": 0.20, "keyword": 0.45, "llm": 0.35}
            self._act(plan, "ADJUST composite_weights: keyword=0.45, llm=0.35",
                "Rich keyword set provides strong signal; weighting it higher.")

        self._observe(plan,
            f"Composite weights → ATS:{plan.composite_weights['ats']} "
            f"KW:{plan.composite_weights['keyword']} LLM:{plan.composite_weights['llm']}")

        # ── Step 4: Experience vs Skills weighting ─────────────────────
        if jd_analysis['seniority_hits']:
            plan.experience_weight = "high"
            plan.debate_weights["experience"] = 0.45
            plan.debate_weights["skill"] = 0.30
            plan.debate_weights["culture"] = 0.25
            self._think(plan,
                f"JD mentions seniority signals: {jd_analysis['seniority_hits'][:3]}",
                "This is a senior role → experience should matter more.")
            self._act(plan, "SET experience_weight=high, debate experience=0.45",
                "Prioritizing experience in debate scoring for senior roles.")
            plan.recommendations.append(
                f"🎯 Senior role detected ({', '.join(jd_analysis['seniority_hits'][:2])}). "
                f"Experience scoring elevated.")

        elif jd_analysis['junior_hits']:
            plan.experience_weight = "low"
            plan.skills_weight = "high"
            plan.debate_weights["skill"] = 0.50
            plan.debate_weights["experience"] = 0.20
            plan.debate_weights["culture"] = 0.30
            self._think(plan,
                f"JD mentions junior signals: {jd_analysis['junior_hits'][:3]}",
                "Junior role → skills/potential matter more than years.")
            self._act(plan, "SET skills_weight=high, experience_weight=low",
                "Prioritizing skills over experience for junior position.")
            plan.recommendations.append(
                "🌱 Junior/entry-level role detected. Skills & potential weighted higher.")

        if len(jd_analysis['tech_hits']) >= 5:
            plan.skills_weight = "high"
            if plan.debate_weights["skill"] < 0.45:
                plan.debate_weights["skill"] = 0.45
                plan.debate_weights["culture"] = 0.20
            self._think(plan,
                f"JD is highly technical: {jd_analysis['tech_hits'][:5]}",
                "Many technical requirements → skill evaluation is critical.")
            self._act(plan, "SET skills_weight=high, debate skill=0.45",
                "Highly technical JD; increasing skill analyst weight.")
            plan.recommendations.append(
                f"🔧 Highly technical role ({len(jd_analysis['tech_hits'])} tech keywords). "
                f"Skill analysis emphasized.")

        if len(jd_analysis['soft_hits']) >= 3:
            plan.debate_weights["culture"] = max(plan.debate_weights["culture"], 0.30)
            self._think(plan,
                f"JD emphasizes soft skills: {jd_analysis['soft_hits'][:3]}",
                "Many soft skill requirements → culture fit matters more.")
            self._act(plan, "ADJUST debate culture≥0.30",
                "Soft skills emphasis in JD; culture weight elevated.")
            plan.recommendations.append(
                f"🤝 Soft skills emphasized ({', '.join(jd_analysis['soft_hits'][:2])}). "
                f"Culture fit analysis strengthened.")

        # ── Step 5: Education weighting ────────────────────────────────
        if jd_analysis['edu_required']:
            plan.education_weight = "high"
            self._act(plan, "SET education_weight=high",
                "JD requires specific degree; education scoring will be boosted.")
            plan.recommendations.append("🎓 Specific degree requirement detected.")
        elif jd_analysis['edu_preferred']:
            plan.education_weight = "normal"
            self._act(plan, "SET education_weight=normal",
                "JD prefers but doesn't require a degree.")

        # ── Step 6: Stage skip decisions ───────────────────────────────
        if plan.jd_complexity == "simple" and resume_count <= 10:
            plan.run_debate = False
            plan.run_reflection = False
            self._think(plan,
                f"Simple JD + only {resume_count} resumes.",
                "Debate & reflection add overhead for very small batches. Skipping.")
            self._act(plan, "SKIP debate, SKIP reflection",
                "Small batch doesn't need multi-agent debate or reflection loop.")
            plan.recommendations.append(
                "⚡ Lightweight mode: skipping debate & reflection for small batch.")

        # ── Step 7: Time estimation ────────────────────────────────────
        if resume_count <= 10:
            plan.estimated_time = "~30 sec"
        elif resume_count <= 50:
            plan.estimated_time = "~2 min"
        elif resume_count <= 200:
            plan.estimated_time = "~5 min"
        else:
            plan.estimated_time = "~10+ min"

        # ── Step 8: Strategy label ─────────────────────────────────────
        if plan.jd_complexity == "complex":
            plan.strategy_label = "🔬 Deep Analysis Pipeline"
        elif plan.jd_complexity == "simple":
            if plan.run_debate:
                plan.strategy_label = "⚡ Standard Pipeline"
            else:
                plan.strategy_label = "⚡ Lightweight Fast Pipeline"
        else:
            plan.strategy_label = "🎯 Balanced Pipeline"

        if not plan.recommendations:
            plan.recommendations.append("✅ Standard pipeline configuration — no special adjustments needed.")

        self._observe(plan,
            f"Strategy: {plan.strategy_label} | "
            f"Est. time: {plan.estimated_time} | "
            f"Stages: {sum([plan.run_ats_filter, plan.run_extraction, plan.run_scoring, plan.run_reflection, plan.run_debate, plan.run_insights])}/6")

        # ── Step 9: Optional LLM-enhanced reasoning ────────────────────
        llm_reasoning = self._llm_reason(job_description, plan, jd_analysis, resume_count, keyword_count)
        if llm_reasoning:
            plan.reasoning_steps.append({
                "phase": "LLM_REASONING",
                "output": llm_reasoning,
            })

        return plan

    def _llm_reason(self, job_description, plan, jd_analysis, resume_count, keyword_count):
        """Optional LLM call for deeper strategic reasoning."""
        if not self.llm_agent:
            return None

        prompt = f"""You are an AI Pipeline Strategist. Given the job description and dataset size,
briefly validate or adjust the pipeline strategy.

Job Description (first 800 chars):
{job_description[:800]}

Dataset: {resume_count} resumes, {keyword_count} keywords
Complexity: {plan.jd_complexity}
Strategy: {plan.strategy_label}
Weights: Experience={plan.experience_weight}, Skills={plan.skills_weight}
Key JD Signals: seniority={jd_analysis['seniority_hits'][:2]}, tech={jd_analysis['tech_hits'][:3]}

In 2-3 sentences, confirm this strategy is reasonable OR suggest a change.
Start with "Strategy: APPROVED" or "Strategy: ADJUST"."""

        try:
            response, elapsed = self.llm_agent.call_llm(
                self.llm_agent.MODELS.get("insights", "llama3:latest"),
                prompt, timeout=15
            )
            return response if response else None
        except Exception:
            return None

    def format_plan_summary(self, plan):
        """Format the plan as a human-readable markdown summary."""
        lines = [f"## 🧠 AI Strategy: {plan.strategy_label}\n"]
        lines.append(f"**Complexity:** {plan.jd_complexity.title()} | "
                     f"**Est. Time:** {plan.estimated_time}\n")

        # Recommendations
        if plan.recommendations:
            lines.append("### Recommendations")
            for r in plan.recommendations:
                lines.append(f"- {r}")
            lines.append("")

        # Weight configuration
        lines.append("### Weight Configuration")
        lines.append(f"| Component | Weight |")
        lines.append(f"|---|---|")
        lines.append(f"| ATS Score | {plan.composite_weights['ats']:.0%} |")
        lines.append(f"| Keyword Match | {plan.composite_weights['keyword']:.0%} |")
        lines.append(f"| LLM Score | {plan.composite_weights['llm']:.0%} |")
        lines.append(f"| Debate: Skill | {plan.debate_weights['skill']:.0%} |")
        lines.append(f"| Debate: Experience | {plan.debate_weights['experience']:.0%} |")
        lines.append(f"| Debate: Culture | {plan.debate_weights['culture']:.0%} |")
        lines.append("")

        # Stage status
        stages = [
            ("ATS Filtering", plan.run_ats_filter, f"top_n={plan.ats_top_n}"),
            ("LLM Extraction", plan.run_extraction, "Qwen"),
            ("LLM Scoring", plan.run_scoring, "Mistral"),
            ("Self-Correction", plan.run_reflection, "Reflection Agent"),
            ("Multi-Agent Debate", plan.run_debate, "3 Agents + Devil's Advocate"),
            ("Final Insights", plan.run_insights, "LLaMA"),
        ]
        lines.append("### Pipeline Stages")
        for label, enabled, detail in stages:
            icon = "✅" if enabled else "⏭️"
            status = "Enabled" if enabled else "**Skipped**"
            lines.append(f"- {icon} **{label}** — {status} ({detail})")

        return "\n".join(lines)

    def format_reasoning_trace(self, plan):
        """Format the ReAct reasoning trace for display."""
        lines = []
        for i, step in enumerate(plan.reasoning_steps):
            phase = step.get('phase', '?')
            if phase == "THINK":
                lines.append(
                    f"💭 **THINK:** {step.get('observation', '')}\n"
                    f"   → {step.get('thought', '')}"
                )
            elif phase == "ACT":
                lines.append(
                    f"⚡ **ACT:** `{step.get('action', '')}`\n"
                    f"   → {step.get('detail', '')}"
                )
            elif phase == "OBSERVE":
                lines.append(f"👁️ **OBSERVE:** {step.get('result', '')}")
            elif phase == "LLM_REASONING":
                lines.append(f"🤖 **LLM Validation:** {step.get('output', '')[:300]}")
        return "\n\n".join(lines)
